# ---------- Stage 1: Frontend Build ----------
FROM node:20 AS frontend-builder

WORKDIR /Frontend

COPY Frontend/package*.json ./
RUN npm install

COPY Frontend/ .
RUN npm run build


# ---------- Stage 2: Backend ----------
FROM node:20-slim 

WORKDIR /app

# install only backend deps
COPY Backend/package*.json ./
RUN npm install --omit=dev   

# copy backend code
COPY Backend/ .

# copy frontend build
COPY --from=frontend-builder /Frontend/dist ./public
#  optional but good practice
ENV NODE_ENV=production

CMD ["node", "server.js"]